DB_CONFIG = {
    "dialect": "postgresql",
    "username": "avnadmin",
    "password": "AVNS_0RqM2QO8lu8nstmTVzW",
    "host": "cmconnect2025-26-sanjushusanth-a5cb.i.aivencloud.com",
    "port": "11350",
    "database": "defaultdb"
}